WebEmpleados/WebEmpleados/urls.py
from django.contrib import admin
from django.urls import path, include

#PARA GENERAR URL ESTATICAS Y PODER VISUALIZAR IMAGENES CARGADAS
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('applications.home.urls') , name='home'),
    path('', include('applications.persona.urls'), name='empleados'),
    path('departamentos/', include('applications.departamento.urls'), name='departamentos')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#PERMITIR VER IMAGENES DESDE NUESTRO SERVIDOR

WebEmpleados/applications/departamento/urls.py
from django.urls import path
from .views import *

app_name = "departamento_app"

urlpatterns = [
    path('', DepartamentoPageView.as_view(), name='departamentos-list'),
    path('agregar-departamento/', RegistrarDepartamentoFormView.as_view(), name='departamento-add')
]

WebEmpleados/applications/persona/urls.py
from django.urls import path
from .views import *

app_name = "persona_app"

urlpatterns = [
    path('', InicioView.as_view(), name='inicio'),
    path('lista-empleados/', EmpleadoListView.as_view(), name='empleado-list'),
    path('admin-empleados/', AdminEmpleadoListView.as_view(), name='admin-empleado-list'),
    path('lista-areas/<shortname>', AreaEmpleadoListView.as_view(), name='area-empleado-list'),
    path('search-empleado/', EmpleadosBusquedaListView.as_view(), name='search-empleado'),
    path('lista-habilidades-empleado/<int:idEmpleado>/', HabilidadesEmpleadoListView.as_view(), name='empleado-habilidades-list'),
    path('detalle-empleado/<int:pk>/', EmpleadoDetailView.as_view(), name='empleado-detail'),
    path('agregar-empleado/', EmpleadoCreateView.as_view(), name='empleado-add'),
    path('editar-empleado/<int:pk>/', EmpleadoUpdateView.as_view(), name='empleado-edit'),
    path('eliminar-empleado/<int:pk>/', EmpleadoDeleteView.as_view(), name='empleado-delete')
]

WebEmpleados/applications/departamento/models.py
from django.db import models

# Create your models here.
class Departamento(models.Model):
    name = models.CharField('Nombre', max_length=50)
    short_name = models.CharField('Nombre Corto', max_length=20, unique=True)
    anulate = models.BooleanField('Anulado', default=False)

    class Meta:
        ordering = ['-name']
        unique_together = ('name', 'short_name')

    def __str__(self):
        return str(self.id) + '-' + self.name + '-' + self.short_name

WebEmpleados/applications/departamento/forms.py
from django import forms

class NuevoDepartamentoForm(forms.Form):
    
    nombre = forms.CharField(max_length=50)
    apellidos = forms.CharField(max_length=50)
    departamento = forms.CharField(max_length=50, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Escriba el departamento...'}))
    shortname = forms.CharField(max_length=20, widget=forms.TextInput(attrs={'class':'form-control', 'placeholder':'Escriba el nombre corto...'}))

WebEmpleados/applications/departamento/views.py
from django.http import HttpResponse
from django.shortcuts import render
from .forms import NuevoDepartamentoForm
from django.views.generic.edit import FormView
from django.views.generic.list import ListView
from django.urls import reverse_lazy
from applications.persona.models import Empleado
from .models import Departamento

class DepartamentoPageView(ListView):
    model = Departamento
    context_object_name = 'departamentos'
    template_name = 'departamento/departamentos.html'

class RegistrarDepartamentoFormView(FormView):
    template_name = 'departamento/agregar-departamento.html'
    form_class = NuevoDepartamentoForm
    success_url = reverse_lazy('departamento_app:departamento-add')


    def form_valid(self, form):
        print('******************Estamos en el Form Valid*****************')
        
        depa = Departamento(
            name = form.cleaned_data['departamento'],
            short_name = form.cleaned_data['shortname']
        )

        depa.save()
        
        nombre = form.cleaned_data['nombre']
        apellidos = form.cleaned_data['apellidos']
        Empleado.objects.create(
            first_name = nombre,
            last_name = apellidos,
            full_name = nombre + ' ' + apellidos,
            job = '1',
            departamento =  depa
        )


        return super().form_valid(form)

WebEmpleados/templates/departamento/agregar-departamento.html
{% extends 'base.html' %} 

{% block content %}

<div class="container">
  <div class="card shadow mt-3">
    <div class="card-header bg-primary text-white">
      <h4>Agregar Departamento</h4>
    </div>
    <div class="card-body">
      <form method="post">
        {% csrf_token %}
        <h5 class="fw-bold">Datos Empleado</h5>
            <label class="text-primary fw-bold">Nombres:</label>
            <input type="text" name="{{ form.nombre.name }}" class="form-control" maxlength="50" placeholder="Escriba sus nombres...">
            <br>
            <label class="text-primary fw-bold">Apellidos:</label>
            <input type="text" name="{{ form.apellidos.name }}" class="form-control" maxlength="50" placeholder="Escriba sus apellidos...">
        <br>
        <h5 class="fw-bold">Datos Departamento</h5>
        <p><label class="text-primary fw-bold">Departamento:</label> {{ form.departamento }}</p>
        <p><label class="text-primary fw-bold">Short Name:</label> {{ form.shortname }}</p>
        <hr>
        <div class="d-grid gap-1">
          <button type="submit" class="btn btn-success">Guardar</button>
        </div>
      </form>
    </div>
  </div>
</div>

{% endblock content %}

WebEmpleados/templates/departamento/departamentos.html
{% extends 'base.html' %}

{% block content %}
<div class="container mt-3">
    <div class="card shadow">
        <div class="card-header bg-primary text-white"><h4>Departamentos</h4></div>
        <div class="card-body">
            <div class="table-responsive">
                <table class="table table-bordered table-striped" id="example" style="width:100%">
                    <thead>
                        <tr>
                            <th>#</th>
                            <th>Nombre</th>
                            <th>Nombre Corto</th>
                            <th>Acciones</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for departamento in departamentos %}
                            <tr>
                                <td>{{departamento.id}}</td>
                                <td>{{departamento.name}}</td>
                                <td>{{departamento.short_name}}</td>
                                <td><a class="btn btn-info btn-sm text-white" href="{% url 'persona_app:area-empleado-list' departamento.short_name %}">Ver Empleados</a></td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock content %}