WebEmpleados/WebEmpleados/urls.py
from django.contrib import admin
from django.urls import path, include

#PARA GENERAR URL ESTATICAS Y PODER VISUALIZAR IMAGENES CARGADAS
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('applications.home.urls') , name='home'),
    path('', include('applications.persona.urls'), name='empleados'),
    path('departamentos/', include('applications.departamento.urls'), name='departamentos')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#PERMITIR VER IMAGENES DESDE NUESTRO SERVIDOR

WebEmpleados/applications/departamento/urls.py
from django.urls import path
from .views import *

app_name = "departamento_app"

urlpatterns = [
    path('', DepartamentoPageView.as_view(), name='departamentos-list'),
    path('agregar-departamento/', RegistrarDepartamentoFormView.as_view(), name='departamento-add')
]

WebEmpleados/applications/persona/urls.py
from django.urls import path
from .views import *

app_name = "persona_app"

urlpatterns = [
    path('', InicioView.as_view(), name='inicio'),
    path('lista-empleados/', EmpleadoListView.as_view(), name='empleado-list'),
    path('admin-empleados/', AdminEmpleadoListView.as_view(), name='admin-empleado-list'),
    path('lista-areas/<shortname>', AreaEmpleadoListView.as_view(), name='area-empleado-list'),
    path('search-empleado/', EmpleadosBusquedaListView.as_view(), name='search-empleado'),
    path('lista-habilidades-empleado/<int:idEmpleado>/', HabilidadesEmpleadoListView.as_view(), name='empleado-habilidades-list'),
    path('detalle-empleado/<int:pk>/', EmpleadoDetailView.as_view(), name='empleado-detail'),
    path('agregar-empleado/', EmpleadoCreateView.as_view(), name='empleado-add'),
    path('editar-empleado/<int:pk>/', EmpleadoUpdateView.as_view(), name='empleado-edit'),
    path('eliminar-empleado/<int:pk>/', EmpleadoDeleteView.as_view(), name='empleado-delete')
]

WebEmpleados/templates/includes/footer.html
<footer class="mt-5 pt-2" style="background-color: #7C9885;">
	<div class="container">
		<div class="row">
			<div class="container">
				<div class="d-flex justify-content-between align-items-center py-3 text-center">
					<!-- copyright text -->
					<div class="text-white"> Copyrights ©2023 Cristian Hortua. Build by <a href="https://www.cristianhortua.com/" class="text-white">CasTech</a>. </div>
					<!-- copyright links-->
					<div class="nav mt-2 mt-lg-0">
						<ul class="list-inline mx-auto mb-0">
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-white" href="#">Privacy policy</a></li>
							<li class="list-inline-item me-0"><a class="nav-link py-1 text-white" href="#">Terms and conditions</a></li>
							<li class="list-inline-item me-0"><a class="nav-link py-1 pe-0 text-white" href="#">Refund policy</a></li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</footer>

WebEmpleados/templates/includes/header.html
<nav class="navbar navbar-expand-xl shadow-sm" style="background-color: #033F63;">
    <div class="container">
        <a class="navbar-brand text-white" href="{% url 'persona_app:inicio' %}"><h2>Empleados</h2></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'persona_app:empleado-list' %}">Listar</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'departamento_app:departamentos-list' %}">Departamentos</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link text-white" href="{% url 'persona_app:admin-empleado-list' %}">Administrar</a>
                </li>
            </ul>
        </div>
        <ul class="navbar-nav">
            <!--
            <form class="d-flex" role="search">
                <input class="form-control form-control-sm me-2" type="search" placeholder="Buscar Empleado" aria-label="Search">
            </form>-->
            <li class="nav-item">
                <a class="btn btn-success btn-sm text-white" href="{% url 'persona_app:empleado-add' %}">Registrar Nuevo</a>
            </li>
        </ul>
    </div>
</nav>