WebEmpleados/WebEmpleados/urls.py
from django.contrib import admin
from django.urls import path, include

#PARA GENERAR URL ESTATICAS Y PODER VISUALIZAR IMAGENES CARGADAS
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('home/', include('applications.home.urls') , name='home'),
    path('', include('applications.persona.urls'), name='empleados'),
    path('departamentos/', include('applications.departamento.urls'), name='departamentos')
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#PERMITIR VER IMAGENES DESDE NUESTRO SERVIDOR

WebEmpleados/applications/persona/urls.py
from django.urls import path
from .views import *

app_name = "persona_app"

urlpatterns = [
    path('', InicioView.as_view(), name='inicio'),
    path('lista-empleados/', EmpleadoListView.as_view(), name='empleado-list'),
    path('admin-empleados/', AdminEmpleadoListView.as_view(), name='admin-empleado-list'),
    path('lista-areas/<shortname>', AreaEmpleadoListView.as_view(), name='area-empleado-list'),
    path('search-empleado/', EmpleadosBusquedaListView.as_view(), name='search-empleado'),
    path('lista-habilidades-empleado/<int:idEmpleado>/', HabilidadesEmpleadoListView.as_view(), name='empleado-habilidades-list'),
    path('detalle-empleado/<int:pk>/', EmpleadoDetailView.as_view(), name='empleado-detail'),
    path('agregar-empleado/', EmpleadoCreateView.as_view(), name='empleado-add'),
    path('editar-empleado/<int:pk>/', EmpleadoUpdateView.as_view(), name='empleado-edit'),
    path('eliminar-empleado/<int:pk>/', EmpleadoDeleteView.as_view(), name='empleado-delete')
]

WebEmpleados/applications/persona/models.py
from django.db import models
from applications.departamento.models import Departamento
from ckeditor.fields import RichTextField

# Create your models here.
class Habilidades(models.Model):
    habilidad = models.CharField('Habilidad', max_length=50)

    class Meta:
        verbose_name = 'Habilidades'
        verbose_name_plural = 'Habilidades'

    def __str__(self):
        return str(self.id) + '-' + self.habilidad

class Empleado(models.Model):

    job_choices = (
        ('0', 'Contador'), 
        ('1', 'Administrador'), 
        ('2', 'Economista'), 
        ('3', 'Otro')
    )

    first_name = models.CharField('Nombres', max_length=60)
    last_name = models.CharField('Apellidos', max_length=60)
    full_name = models.CharField('Nombres Completos', max_length=120, blank=True)
    job = models.CharField('Trabajo', max_length=1, choices=job_choices)
    departamento = models.ForeignKey(Departamento, on_delete=models.CASCADE)
    avatar = models.ImageField(upload_to='empleado', blank=True, null=True)
    habilidades = models.ManyToManyField(Habilidades)
    hoja_vida = RichTextField()


    class Meta:
        ordering = ['-first_name', 'last_name']
        unique_together = ('first_name', 'departamento')

    def __str__(self):
        return str(self.id) + '-' + self.first_name + '-' + self.last_name

WebEmpleados/applications/persona/forms.py
from django import forms
from .models import Empleado

class EmpleadoUpdateForm(forms.ModelForm):

    class Meta:
        model = Empleado
        fields = ['first_name', 'last_name', 'job', 'departamento', 'habilidades', 'hoja_vida', 'avatar']
        #fields = ('__all__')

        widgets = {

            'first_name': forms.TextInput(attrs={'placeholder':'Escriba su nombre', 'class':'form-control'}),
            'last_name': forms.TextInput(attrs={'placeholder':'Escriba su apellido', 'class':'form-control'}),
            'job': forms.Select(attrs={'class':'form-control'}, choices=Empleado.job_choices),
            'departamento': forms.Select(attrs={'class':'form-control'}),
            'habilidades': forms.CheckboxSelectMultiple(),
            'avatar': forms.ClearableFileInput(attrs={'class':'form-control'}),
            'hoja_vida': forms.Textarea(attrs={'class':'form-control'})
        }

    '''
    def clean_cantidad(self):
        cantidad = self.cleaned_data['cantidad']
        if cantidad < 10:
            raise forms.ValidationError('Ingrese un numero mayor a 10')
        
        return cantidad
    '''

WebEmpleados/applications/persona/views.py
from typing import Any
from django.db.models.query import QuerySet
from django.forms.models import BaseModelForm
from django.http import HttpResponse
from django.shortcuts import render
from django.views.generic import ListView, DetailView, TemplateView
from .models import Empleado
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.urls import reverse_lazy
from .forms import EmpleadoUpdateForm


# Create your views here.

class InicioView(TemplateView):
    template_name = 'inicio.html'

class AdminEmpleadoListView(ListView):
    model = Empleado
    template_name = 'persona/admin-empleados.html'
    context_object_name = 'listaEmpleados'
    ordering = 'first_name'

class EmpleadoListView(ListView):
    model = Empleado
    template_name = 'persona/list-empleados.html'
    context_object_name = 'listaEmpleados'
    ordering = 'first_name'

class AreaEmpleadoListView(ListView):
    template_name = 'persona/list-area.html'
    #Filtrar la busqueda por el name de la tabla Departamento
    #queryset = Empleado.objects.filter(departamento__name='Economia y Finanzas')
    context_object_name = 'listAreasEmpleados'

    def get_queryset(self):
        area = self.kwargs['shortname']
        lista = Empleado.objects.filter(departamento__short_name=area)
        return lista
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        print(self.kwargs)
        context['departamento'] = self.kwargs['shortname']
        return context

class EmpleadosBusquedaListView(ListView):
    template_name = 'persona/busqueda-empleados.html'
    context_object_name = 'listaBusqueda'

    def get_queryset(self):
        if self.request.GET:
            palabraClave = self.request.GET['kword']
            lista = Empleado.objects.filter(first_name=palabraClave)
            return lista
        
class HabilidadesEmpleadoListView(ListView):
    template_name = 'persona/list-habilidades-empleado.html'
    context_object_name = 'listaHabilidades'

    def get_queryset(self):
        idEmpleado = self.kwargs['idEmpleado']
        #Recuperando 1 registro de Empleados
        empleado = Empleado.objects.get(id=idEmpleado)
        habilidades = empleado.habilidades.all()
        return habilidades
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        idEmpleado = self.kwargs['idEmpleado']
        context['empleado'] = Empleado.objects.get(id=idEmpleado)
        return context
    
class EmpleadoDetailView(DetailView):
    model = Empleado
    template_name = 'persona/detail-empleado.html'

class EmpleadoCreateView(CreateView):
    model = Empleado
    template_name = 'persona/agregar-empleado.html'
    #fields = ['first_name', 'last_name', 'job', 'departamento', 'hoja_vida', 'habilidades']
    form_class = EmpleadoUpdateForm
    success_url = reverse_lazy('persona_app:admin-empleado-list')

    def form_valid(self, form):
        empleado = form.save(commit=False)
        empleado.full_name = empleado.first_name + ' ' + empleado.last_name
        empleado.save()
        return super(EmpleadoCreateView, self).form_valid(form)
    
class EmpleadoUpdateView(UpdateView):
    model = Empleado
    template_name = 'persona/editar-empleado.html'
    #fields = ['first_name', 'last_name', 'job', 'departamento', 'hoja_vida', 'habilidades']
    success_url = reverse_lazy('persona_app:admin-empleado-list')
    form_class = EmpleadoUpdateForm

    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        #print(request.POST)
        #print(request.POST['last_name'])
        return super().post(request, *args, **kwargs)
    
class EmpleadoDeleteView(DeleteView):
    model = Empleado
    template_name = 'persona/eliminar-empleado.html'

    success_url = reverse_lazy('persona_app:admin-empleado-list')

WebEmpleados/templates/persona/admin-empleados.html
{% extends 'base.html' %}

{% block title %} Lista Empleados {% endblock title %}


{% block content %}

    <section class="pt-3 pt-lg-5">
        <div class="container">
            <h4 style="color: #28666E;">Administrar Empleados</h4>
            <div class="card shadow-sm mb-4 mt-4">
                <div class="card-body">
                    <a class="btn btn-success btn-sm mb-4" href="{% url 'persona_app:empleado-add' %}">Agregar Empleado</a>
                    
                    <div class="table-responsive">
                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nombre</th>
                                    <th>Job</th>
                                    <th>Departamento</th>
                                    <th>Acciones</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for empleado in listaEmpleados %}

                                    <tr>
                                        <td>{{ empleado.id }}</td>
                                        <td>{{ empleado }}</td>
                                        <td>{{ empleado.get_job_display }}</td>
                                        <td>{{ empleado.departamento }}</td>
                                        <td><a class="btn btn-info btn-sm text-white" href="{% url 'persona_app:empleado-detail' empleado.id %}">Ver</a> <a class="btn btn-primary btn-sm" href="{% url 'persona_app:empleado-edit' empleado.id %}">Editar</a> <a class="btn btn-danger btn-sm" href="{% url 'persona_app:empleado-delete' empleado.id %}">Eliminar</a></td>
                                    </tr>
                                
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>

                </div>

                <!--
                <ul>
                    {% for empleado in listaEmpleados %}
                        <li>{{ empleado }} <a href="{% url 'persona_app:empleado-detail' empleado.id %}">Ver</a> | <a href="{% url 'persona_app:empleado-edit' empleado.id %}">Editar</a> | <a href="{% url 'persona_app:empleado-delete' empleado.id %}">Eliminar</a></li>
                    {% endfor %}
                    
                </ul>


                {% if is_paginated %}
                    <ul>
                        {% if page_obj.has_previous %}

                            <li><a href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>

                        {% else %}
                    
                            <li><a href="#">&laquo;</a></li>

                        {% endif %}

                        {% for i in paginator.page_range %}

                            <li><a href="?page={{i}}">{{i}}</a></li>

                        {% endfor %}

                        {% if page_obj.has_next %}

                            <li><a href="?page={{page_obj.next_page_number}}">&raquo;</a></li>


                        {% else %}
                    
                            <li><a href="#">&raquo;</a></li>

                        {% endif %}


                    </ul>

                {% endif %}
                -->

            </div>
        </div>
    </section>


{% endblock content %}

WebEmpleados/templates/persona/agregar-empleado.html
{% extends 'base.html' %}



{% block content %}

<div class="container">
    <div class="card shadow mt-3">
        <div class="card-header bg-primary text-white">
            <h4>Crear Empleado</h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="row">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Nombres:</label>
                        {{ form.first_name }}
                    </div>
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Apellidos:</label>
                        {{ form.last_name }}
                    </div>

                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Trabajo:</label>
                        {{ form.job }}
                    </div>
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Departamento:</label>
                        {{ form.departamento }}
                    </div>

                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Habilidades:</label>
                        {{ form.habilidades }}
                    </div>
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Hoja de Vida:</label>
                        {{ form.hoja_vida }}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Avatar:</label>
                        {{ form.avatar }}
                    </div>
                </div>
                <hr>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

WebEmpleados/templates/persona/busqueda-empleados.html
<h1>Buscar Empleados</h1>
<form method="GET">
    {% csrf_token %}
    <input type="text" id="kword" name="kword" placeholder="Ingrese palabra clave">
    <button type="submit">Buscar</button>
</form>

{% if listaBusqueda %}

    <h3>Resultados encontrados: </h3>

    <ul>

        {% for empleado in listaBusqueda %}

            <li>{{empleado}}</li>

        {% endfor %}

    </ul>

{% endif %}

WebEmpleados/templates/persona/detail-empleado.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-3">
    <div class="card">
        
        <div class="card-header bg-primary text-white">

            <h4>Datos Empleado</h4>

        </div>

        <div class="card-body">
            <div class="row">
                <div class="col-md-8">
                    <p><b class="text-primary">Nombre:</b> {{ empleado.first_name }} {{ empleado.last_name }}</p>
                    <p><b class="text-primary">Trabajo:</b> {{ empleado.get_job_display }}</p>
                    <p><b class="text-primary">Departamento:</b> {{ empleado.departamento }}</p>
                    <p><b class="text-primary">Hoja Vida:</b> {{ empleado.hoja_vida|safe }}</p>
                </div>
                <div class="col-md-4">
                    <p><b class="text-primary">Avatar</b></p>
                    {% if empleado.avatar %}

                        <img class="img-thumbnail" style="width: 300px; height: 300;" src="{{ empleado.avatar.url }}">

                    {% else %}

                        {% load static %}

                        <img class="img-thumbnail" style="width: 300px; height: 300;" src="{% static 'img/no-profile.png' %}">

                    {% endif %}

                </div>
            </div>
            <hr>
            <h5 class="text-primary">Habilidades</h5>

            {% for h in empleado.habilidades.all %}

                <p>{{ h.habilidad }}</p>

            {% endfor %}

        </div>

    </div>
</div>

{% endblock content %}

WebEmpleados/templates/persona/editar-empleado.html
{% extends 'base.html' %}

{% block content %}

<div class="container mt-3">
    <div class="card">
        <div class="card-header bg-primary text-white">
            <h4>Editar Empleado</h4>
        </div>
        <div class="card-body">
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                
                <div class="row">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Nombres:</label>
                        {{ form.first_name }}
                    </div>
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Apellidos:</label>
                        {{ form.last_name }}
                    </div>

                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Trabajo:</label>
                        {{ form.job }}
                    </div>
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Departamento:</label>
                        {{ form.departamento }}
                    </div>

                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Habilidades:</label>
                        {{ form.habilidades }}
                    </div>
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Hoja de Vida:</label>
                        {{ form.hoja_vida }}
                    </div>
                </div>
                <div class="row mt-2">
                    <div class="col-md-6">
                        <label class="text-primary fw-bold">Avatar:</label>
                        {% if object.avatar %}

                            <img class="img-fluid" src="{{ object.avatar.url }}" alt="avatar">

                        {% endif %}
                        
                        {{ form.avatar }}
                    </div>
                </div>

                <hr>
                <div class="d-grid gap-2">
                    <button type="submit" class="btn btn-success">Guardar</button>
                </div>
            </form>
            
        </div>
    </div>
</div>
    
{% endblock content %}

WebEmpleados/templates/persona/eliminar-empleado.html
{% extends 'base.html' %}


{% block content %}

<div class="container">
    <div class="card shadow mt-3">
        <div class="card-header bg-danger text-white">
            <h4>Eliminar Empleado</h4>
        </div>
        <div class="card-body">
            <form method="post">
                {% csrf_token %}
                <p>Desea eliminar el registro <b>"{{ object }}"</b> ?</p>
                {{ form }}
                <button type="submit" class="btn btn-danger">Eliminar</button>
                <a class="btn btn-warning text-white" href="{% url 'persona_app:empleado-list' %}">Cancelar</a>
            </form>
        </div>
    </div>
</div>

{% endblock content %}

WebEmpleados/templates/persona/list-area.html
{% extends 'base.html' %}


{% block content %}

<div class="container mt-3">
    <div class="card">
        <div class="card-header bg-primary text-white"><h3>Lista Empleados Departamento: {{ departamento }}</h3></div>
        <div class="card-body">
            <ul>
                {% for empleado in listAreasEmpleados %}
            
                    <li>{{ empleado.first_name }} {{ empleado.last_name }}</li>
            
                {% endfor %}
            </ul>
        </div>
    </div>
</div>

{% endblock content %}

WebEmpleados/templates/persona/list-empleados.html
{% extends 'base.html' %}

{% block title %} Lista Empleados {% endblock title %}


{% block content %}

    <section class="pt-3 pt-lg-5">
        <div class="container">
            <h4 style="color: #28666E;">Lista Empleados</h4>
            <div class="card shadow-sm mb-4 mt-4">
                <div class="card-body">

                    <div class="table-responsive">
                        <table id="example" class="table table-striped table-bordered" style="width:100%">
                            <thead>
                                <tr>
                                    <th>#</th>
                                    <th>Nombre</th>
                                    <th>Job</th>
                                    <th>Departamento</th>
                                </tr>
                            </thead>
                            <tbody>
                                
                                {% for empleado in listaEmpleados %}

                                    <tr>
                                        <td>{{ empleado.id }}</td>
                                        <td>{{ empleado }}</td>
                                        <td>{{ empleado.get_job_display }}</td>
                                        <td>{{ empleado.departamento }}</td>
                                    </tr>
                                
                                {% endfor %}

                            </tbody>
                        </table>
                    </div>

                </div>

                <!--
                <ul>
                    {% for empleado in listaEmpleados %}
                        <li>{{ empleado }} <a href="{% url 'persona_app:empleado-detail' empleado.id %}">Ver</a> | <a href="{% url 'persona_app:empleado-edit' empleado.id %}">Editar</a> | <a href="{% url 'persona_app:empleado-delete' empleado.id %}">Eliminar</a></li>
                    {% endfor %}
                    
                </ul>


                {% if is_paginated %}
                    <ul>
                        {% if page_obj.has_previous %}

                            <li><a href="?page={{page_obj.previous_page_number}}">&laquo;</a></li>

                        {% else %}
                    
                            <li><a href="#">&laquo;</a></li>

                        {% endif %}

                        {% for i in paginator.page_range %}

                            <li><a href="?page={{i}}">{{i}}</a></li>

                        {% endfor %}

                        {% if page_obj.has_next %}

                            <li><a href="?page={{page_obj.next_page_number}}">&raquo;</a></li>


                        {% else %}
                    
                            <li><a href="#">&raquo;</a></li>

                        {% endif %}


                    </ul>

                {% endif %}
                -->

            </div>
        </div>
    </section>


{% endblock content %}

WebEmpleados/templates/persona/list-habilidades-empleado.html
<h1>Habilidades Empleado: {{ empleado }}</h1>

<ul>

    {% for habilidad in listaHabilidades %}

        <li>{{ habilidad }}</li>

    {% endfor %}
</ul>